[tool.ruff]
indent-width = 4
line-length = 88
target-version = "py38"
cache-dir = "~/.cache/ruff"
fix=true
unsafe-fixes=true

[tool.ruff.format]
quote-style = "double"
docstring-code-format = true
skip-magic-trailing-comma = true
line-ending = "auto"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "W5", "F", "I"]

[tool.ruff.lint.isort]
length-sort = true
